spring:
    application:
        name: poolcare-api
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASS}
server:
    port: 8080
    servlet:
        context-path: /api/v1
logging:
    level:
        root: info
# TODO: not currently recognizing token
# api:
#     token:
#         secret: ${POOLCARE_API_KEY}
#         enabled: true