openapi: 3.0.1
info:
  title: PoolCare API
  description: PoolCare is a SaaS offering for swimming pool service companies. This api .
  version: 1.0.0
  contact:
    name: Alex Gordon
    url: https://alexrgordon.com
    email: argordon.dev@gmail.com
# base path is not currently recognized from openapi spec
# servers:
#   - url: http://localhost:8080/api/v1
#     description: The poolcare API server
paths:
  '/getCustomersByCompanyId':
    get:
      tags:
        - Poolcare
      description: Returns all of the customers that belong to an organization
      operationId: getCustomersByCompanyId
      parameters:
        - name: companyId
          in: query
          description: The id of the company/business
          example: 123
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
        400:
          description: Bad Request
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'  
  '/addCustomer':
    post:
      tags:
        - Poolcare
      description: Adds a customer to the specified companies database
      operationId: addCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCustomerRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/AddCustomerResponse'
        400:
          description: Bad Request
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/getWorkOrders':
    get:
      tags:
        - Poolcare
      description: Retreives all of the work orders that exist for a specific company
      operationId: getWorkOrders
      parameters:
        - name: companyId
          in: query
          description: The id of the company/business
          example: 123
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkOrder'
        400:
          description: Bad Request
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal Server Error
          content:
            'application/problem+json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas: # Object definition
    CustomerResponse:
      type: object
      properties:
        firstName:
          type: string
          example: Dave
        lastName:
          type: string
          example: Matthews
    AddCustomerRequest:
      type: object
      properties:
        companyName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    AddCustomerResponse:
      type: object
      properties:
        customerId: 
          type: integer
          format: int32
        firstName:
          type: string
        lastName:
          type: string
    WorkOrder:
      type: object
      properties:
        workOrderId:
          type: integer
          format: int32
        companyId:
          type: integer
          format: int32
        customerId:
          type: integer
          format: int32
        created:
          type: string
        scheduled:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: 'There was an error processing your request'
        code:
          type: integer
          format: int32
          example: 500
